export const colors = {
  primary:        '#1d4ed8',
  primaryDark:    '#1e40af',
  primaryLight:   '#dbeafe',
  white:          '#ffffff',
  background:     '#f8f9fa',
  cardBackground: '#ffffff',
  cardAlt:        '#e9f0ff',
  text:           '#212529',
  textWeak:       '#6c757d',
  inputBorder:    '#dee2e6',
  inputBackground:'#ffffff',
  error:          '#dc3545',
  success:        '#198754',
  divider:        '#dee2e6',
  tabActive:      '#1d4ed8',
  tabInactive:    '#6c757d',
  tabActiveBg:    '#dbeafe',
};
